[package]
name = "kvm-proto"
version = "0.0.0"
edition.workspace = true
rust-version.workspace = true
license.workspace = true
repository.workspace = true
publish = false
autotests = false

[dependencies]
bytes = { workspace = true }
h264-reader = { workspace = true }

[dev-dependencies]
sha2 = "0.10"
serde_json = "1"

[[test]]
name = "fixtures"
path = "tests/fixtures.rs"
